# This is a basic workflow to help you get started with Actions

name: DEPLOY_HOMOLOG

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ homolog ]
  pull_request:
    branches: [ homolog ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2
        with:
          # hostname / IP of the server
          HOST: 35.198.30.94
          # ssh port of the server
          PORT: 54742
          # user of the server
          USER: polenmain
          # private ssh key registered on the server
          PRIVATE_SSH_KEY: ${{ secrets.KINSTA_SSH }}
          # command to be executed
          COMMAND: ./deploy.sh
